### PR TITLE
support strings for a clearer fan speed in manager mode

### PR DESCRIPTION
**Pull request by arussellsaw**
Hi! thanks for building this tool, it makes the fan on my x62 so much more manageable!

i wanted to play about with fan thresholds but found the integers pretty confusing, from the comments it seems like you were a bit confused too! :joy: 

I've updated the levels struct to use a string, this way we can do the same long int conversion used by the set-fan-speed command. I took this approach because i don't really know C so this was the most obvious way to do it for me.

### CODE REVIEW

**Comment by bitonic** [comment]
Thanks for the contribution! However, it's not clear to me what problem this PR is solving. More importantly, I don't understand why you removed the comments explaining what the fan levels did for my hardware. Could you clarify?

**Comment by arussellsaw** [comment]
these numbers now work as 0-100 as fan percentage

**Comment by bitonic** [comment]
@arussellsaw I don't see how this change changes anything, apart from storing the number as a string rather than as a byte

**Comment by kivoli** [comment]
Yeah, I feel like @arussellsaw misunderstands the values 0-255 are the accepted input for the back-end and not some arbitrary range. For me it is especially important to use these numerical values since the second batch uses an inverted table with additional gotchas with the values. I have a fork for that …

**Comment by bitonic** [comment]
OK, closing this for now. @arussellsaw if I'm being very slow and I've misunderstood what you're trying to do, please reopen.

**Pull request closed without merging**
